services:
  federation_frontend:
    image: ghcr.io/jeffrey-carr/federation-frontend:latest
    container_name: federation_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - '3001:3000'

  federation_backend:
    image: ghcr.io/jeffrey-carr/federation-backend:latest
    container_name: federation_backend
    restart: unless-stopped
    volumes:
      - ./backend/.env.json:/app/.env.json:ro
    ports:
      - '3101:9999'
